# Generated by Django 4.1.5 on 2023-12-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_title_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='')),
                ('caption', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'media',
            },
        ),
    ]
